# Generated by Django 3.0.7 on 2020-06-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200609_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
