# Generated by Django 3.0.7 on 2020-06-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='typewriter',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
