# Generated by Django 3.0.7 on 2020-06-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_typewriter'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='log',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='test_name',
            field=models.CharField(default='runtest', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='<add tests>', max_length=200),
        ),
    ]
