# Generated by Django 3.0.7 on 2020-06-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200611_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='typewriter',
        ),
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
