# Generated by Django 3.0.7 on 2020-06-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200611_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='popup_id',
            field=models.CharField(default='popup', max_length=20),
        ),
    ]
