# Generated by Django 3.0.7 on 2020-06-12 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_popup_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='popup_id',
        ),
    ]
