# Generated by Django 3.0.7 on 2020-06-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='log',
            field=models.CharField(blank=True, default='empty log', max_length=1000),
        ),
    ]
